//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidClears.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaidClears.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to show/hide the Dungeons overlay.
        /// </summary>
        internal static string CornerIcon_Dungeon {
            get {
                return ResourceManager.GetString("CornerIcon_Dungeon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to show/hide the Raids overlay.
        /// </summary>
        internal static string CornerIcon_Raid {
            get {
                return ResourceManager.GetString("CornerIcon_Raid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to show/hide the Strikes overlay.
        /// </summary>
        internal static string CornerIcon_Strike {
            get {
                return ResourceManager.GetString("CornerIcon_Strike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raid Clears.
        /// </summary>
        internal static string Module_Title {
            get {
                return ResourceManager.GetString("Module_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        internal static string ModuleSettings_OpenSettings {
            get {
                return ResourceManager.GetString("ModuleSettings_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable raid overlay.
        /// </summary>
        internal static string Raid_OverlayEnable {
            get {
                return ResourceManager.GetString("Raid_OverlayEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirit Vale.
        /// </summary>
        internal static string Raid_Wing_1 {
            get {
                return ResourceManager.GetString("Raid_Wing_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vale Guardian.
        /// </summary>
        internal static string Raid_Wing_1_1_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_1_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VG.
        /// </summary>
        internal static string Raid_Wing_1_1_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_1_1_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirit Run.
        /// </summary>
        internal static string Raid_Wing_1_2_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_1_2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SR.
        /// </summary>
        internal static string Raid_Wing_1_2_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_1_2_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gorseval.
        /// </summary>
        internal static string Raid_Wing_1_3_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_1_3_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string Raid_Wing_1_3_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_1_3_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabetha.
        /// </summary>
        internal static string Raid_Wing_1_4_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_1_4_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Raid_Wing_1_4_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_1_4_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SV.
        /// </summary>
        internal static string Raid_Wing_1_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_1_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvation Pass.
        /// </summary>
        internal static string Raid_Wing_2 {
            get {
                return ResourceManager.GetString("Raid_Wing_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slothasor.
        /// </summary>
        internal static string Raid_Wing_2_1_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_2_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Raid_Wing_2_1_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_2_1_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandit Trio.
        /// </summary>
        internal static string Raid_Wing_2_2_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_2_2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B3.
        /// </summary>
        internal static string Raid_Wing_2_2_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_2_2_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matthias Gabrel.
        /// </summary>
        internal static string Raid_Wing_2_3_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_2_3_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string Raid_Wing_2_3_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_2_3_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP.
        /// </summary>
        internal static string Raid_Wing_2_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_2_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stonghold of the Falthful.
        /// </summary>
        internal static string Raid_Wing_3 {
            get {
                return ResourceManager.GetString("Raid_Wing_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escort.
        /// </summary>
        internal static string Raid_Wing_3_1_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_3_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string Raid_Wing_3_1_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_3_1_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Construct.
        /// </summary>
        internal static string Raid_Wing_3_2_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_3_2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KC.
        /// </summary>
        internal static string Raid_Wing_3_2_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_3_2_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twisted Castle.
        /// </summary>
        internal static string Raid_Wing_3_3_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_3_3_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC.
        /// </summary>
        internal static string Raid_Wing_3_3_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_3_3_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xera.
        /// </summary>
        internal static string Raid_Wing_3_4_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_3_4_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string Raid_Wing_3_4_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_3_4_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SofF.
        /// </summary>
        internal static string Raid_Wing_3_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_3_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bastion of the Penitent.
        /// </summary>
        internal static string Raid_Wing_4 {
            get {
                return ResourceManager.GetString("Raid_Wing_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cairn the Indominable.
        /// </summary>
        internal static string Raid_Wing_4_1_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_4_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string Raid_Wing_4_1_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_4_1_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mursaat Overseer.
        /// </summary>
        internal static string Raid_Wing_4_2_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_4_2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MO.
        /// </summary>
        internal static string Raid_Wing_4_2_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_4_2_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samarog.
        /// </summary>
        internal static string Raid_Wing_4_3_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_4_3_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Raid_Wing_4_3_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_4_3_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deimos.
        /// </summary>
        internal static string Raid_Wing_4_4_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_4_4_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string Raid_Wing_4_4_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_4_4_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BotP.
        /// </summary>
        internal static string Raid_Wing_4_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_4_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall of Chains.
        /// </summary>
        internal static string Raid_Wing_5 {
            get {
                return ResourceManager.GetString("Raid_Wing_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soulless Horror.
        /// </summary>
        internal static string Raid_Wing_5_1_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_5_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SH.
        /// </summary>
        internal static string Raid_Wing_5_1_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_5_1_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to River of Souls.
        /// </summary>
        internal static string Raid_Wing_5_2_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_5_2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string Raid_Wing_5_2_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_5_2_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statues of Grenth.
        /// </summary>
        internal static string Raid_Wing_5_3_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_5_3_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Raid_Wing_5_3_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_5_3_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhuum.
        /// </summary>
        internal static string Raid_Wing_5_4_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_5_4_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string Raid_Wing_5_4_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_5_4_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HoC.
        /// </summary>
        internal static string Raid_Wing_5_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_5_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mythwright Gambit.
        /// </summary>
        internal static string Raid_Wing_6 {
            get {
                return ResourceManager.GetString("Raid_Wing_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conjured Amalgamate.
        /// </summary>
        internal static string Raid_Wing_6_1_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_6_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA.
        /// </summary>
        internal static string Raid_Wing_6_1_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_6_1_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twin Largos.
        /// </summary>
        internal static string Raid_Wing_6_2_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_6_2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TL.
        /// </summary>
        internal static string Raid_Wing_6_2_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_6_2_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qadim.
        /// </summary>
        internal static string Raid_Wing_6_3_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_6_3_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q1.
        /// </summary>
        internal static string Raid_Wing_6_3_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_6_3_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MG.
        /// </summary>
        internal static string Raid_Wing_6_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_6_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key of Ahdashim.
        /// </summary>
        internal static string Raid_Wing_7 {
            get {
                return ResourceManager.GetString("Raid_Wing_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gate.
        /// </summary>
        internal static string Raid_Wing_7_1_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_7_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string Raid_Wing_7_1_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_7_1_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardinal Adina.
        /// </summary>
        internal static string Raid_Wing_7_2_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_7_2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string Raid_Wing_7_2_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_7_2_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardinal Sabir.
        /// </summary>
        internal static string Raid_Wing_7_3_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_7_3_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Raid_Wing_7_3_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_7_3_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qadim the Peerless.
        /// </summary>
        internal static string Raid_Wing_7_4_Name {
            get {
                return ResourceManager.GetString("Raid_Wing_7_4_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q2.
        /// </summary>
        internal static string Raid_Wing_7_4_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_7_4_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKoA.
        /// </summary>
        internal static string Raid_Wing_7_Short {
            get {
                return ResourceManager.GetString("Raid_Wing_7_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh data every .
        /// </summary>
        internal static string Setting_APIPoll_Label {
            get {
                return ResourceManager.GetString("Setting_APIPoll_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often should the GW2 API be checked for updated information.
        /// </summary>
        internal static string Setting_APIPoll_Tooltip {
            get {
                return ResourceManager.GetString("Setting_APIPoll_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequenter text color.
        /// </summary>
        internal static string Setting_Dun_ColFreqText_Label {
            get {
                return ResourceManager.GetString("Setting_Dun_ColFreqText_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex color code (#rrggbb) for Paths that count for dungeon frequenter achievement.
        /// </summary>
        internal static string Setting_Dun_ColFreqText_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Dun_ColFreqText_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeon feature is currently disabled.
        /// </summary>
        internal static string Setting_Dun_DisabledWarning {
            get {
                return ResourceManager.GetString("Setting_Dun_DisabledWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Dungeon overlay position.
        /// </summary>
        internal static string Setting_Dun_Drag_Label {
            get {
                return ResourceManager.GetString("Setting_Dun_Drag_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click and drag to reposition the overlay window.
        /// </summary>
        internal static string Setting_Dun_Drag_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Dun_Drag_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable dungeons feature.
        /// </summary>
        internal static string Setting_Dun_Enabled {
            get {
                return ResourceManager.GetString("Setting_Dun_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable all dungeon features.
        /// </summary>
        internal static string Setting_Dun_Enabled_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Dun_Enabled_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable dungeon toolbar button.
        /// </summary>
        internal static string Setting_Dun_Icon_Label {
            get {
                return ResourceManager.GetString("Setting_Dun_Icon_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a button next to Blish on the top left of screen that Shows/Hides the dungeon overlay.
        /// </summary>
        internal static string Setting_Dun_Icon_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Dun_Icon_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide keybind.
        /// </summary>
        internal static string Setting_Dun_Keybind_Label {
            get {
                return ResourceManager.GetString("Setting_Dun_Keybind_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Dun_Keybind_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Dun_Keybind_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable mouse hover tooltips on overlay.
        /// </summary>
        internal static string Setting_Dun_Tooltips_Label {
            get {
                return ResourceManager.GetString("Setting_Dun_Tooltips_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hovering the mouse over an path will display the full name.
        /// </summary>
        internal static string Setting_Dun_Tooltips_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Dun_Tooltips_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dungeons overlay.
        /// </summary>
        internal static string Setting_Dun_Visible_Label {
            get {
                return ResourceManager.GetString("Setting_Dun_Visible_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the dungeons overlay on screen.
        /// </summary>
        internal static string Setting_Dun_Visible_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Dun_Visible_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay background color.
        /// </summary>
        internal static string Setting_Raid_ColBG_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_ColBG_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raid overlay background color.
        /// </summary>
        internal static string Setting_Raid_ColBG_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_ColBG_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared encounter color.
        /// </summary>
        internal static string Setting_Raid_ColClear_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_ColClear_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex color code (#rrggbb) for Encounters that have been cleared this week.
        /// </summary>
        internal static string Setting_Raid_ColClear_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_ColClear_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call of the Mists text color.
        /// </summary>
        internal static string Setting_Raid_ColCotm_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_ColCotm_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex color code (#rrggbb) for Wing and Encounters text during the Call of the Mists week.
        /// </summary>
        internal static string Setting_Raid_ColCotm_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_ColCotm_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emboldened text color.
        /// </summary>
        internal static string Setting_Raid_ColEmbolden_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_ColEmbolden_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex color code (#rrggbb) for Wing and Encounters text during the Emboldened week.
        /// </summary>
        internal static string Setting_Raid_ColEmbolden_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_ColEmbolden_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-cleared encounter color.
        /// </summary>
        internal static string Setting_Raid_ColNotClear_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_ColNotClear_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex color code (#rrggbb) for Encounters that have not been cleared this week.
        /// </summary>
        internal static string Setting_Raid_ColNotClear_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_ColNotClear_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label and Grid text color.
        /// </summary>
        internal static string Setting_Raid_ColText_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_ColText_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex color code (#rrggbb) for label and grid text.
        /// </summary>
        internal static string Setting_Raid_ColText_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_ColText_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the weekly &apos;Call of the Mist&apos; raid wing.
        /// </summary>
        internal static string Setting_Raid_Cotm_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_Cotm_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors the text for the weekly Call of the Mists raid wing\nCall of the Mists doubles all gold in the boss loot chest.
        /// </summary>
        internal static string Setting_Raid_Cotm_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_Cotm_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Raid overlay position.
        /// </summary>
        internal static string Setting_Raid_Drag_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_Drag_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click and drag to reposition the overlay windows.
        /// </summary>
        internal static string Setting_Raid_Drag_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_Drag_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the weekly &apos;Emboldened&apos; raid wing.
        /// </summary>
        internal static string Setting_Raid_Embolden_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_Embolden_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors the text for the weekly Emboldened raid wing\nEmbolden mode increases player health, damage, and healing for each stack.
        /// </summary>
        internal static string Setting_Raid_Embolden_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_Embolden_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid size.
        /// </summary>
        internal static string Setting_Raid_Font_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_Font_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the size of the grid.
        /// </summary>
        internal static string Setting_Raid_Font_Tooptip {
            get {
                return ResourceManager.GetString("Setting_Raid_Font_Tooptip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid opacity.
        /// </summary>
        internal static string Setting_Raid_GridOpacity_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_GridOpacity_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden &lt;---&gt; Fully Visible.
        /// </summary>
        internal static string Setting_Raid_GridOpactiy_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_GridOpactiy_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable raid toolbar button.
        /// </summary>
        internal static string Setting_Raid_Icon_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_Icon_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a button next to Blish on the top left of screen that Shows/Hides the raid overlay.
        /// </summary>
        internal static string Setting_Raid_Icon_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_Icon_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide keybind.
        /// </summary>
        internal static string Setting_Raid_Keybind_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_Keybind_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Raid_Keybind_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_Keybind_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label style.
        /// </summary>
        internal static string Setting_Raid_LabelDisplay_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_LabelDisplay_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Raid_LabelDisplay_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_LabelDisplay_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label opacity.
        /// </summary>
        internal static string Setting_Raid_LabelOpacity_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_LabelOpacity_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden &lt;---&gt; Fully Visible.
        /// </summary>
        internal static string Setting_Raid_LabelOpacity_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_LabelOpacity_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid layout.
        /// </summary>
        internal static string Setting_Raid_Layout_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_Layout_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Raid_Layout_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_Layout_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid background opacity.
        /// </summary>
        internal static string Setting_Raid_PanelOpacity_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_PanelOpacity_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden &lt;---&gt; Fully Visible.
        /// </summary>
        internal static string Setting_Raid_PanelOpacity_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_PanelOpacity_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable mouse hover tooltips on overlay.
        /// </summary>
        internal static string Setting_Raid_Tooltips_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_Tooltips_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hovering the mouse over an encounter will display the full name.
        /// </summary>
        internal static string Setting_Raid_Tooltips_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_Tooltips_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable raid overlay.
        /// </summary>
        internal static string Setting_Raid_Visible_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_Visible_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the raid overlay on screen.
        /// </summary>
        internal static string Setting_Raid_Visible_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_Visible_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W1 / Spirit Vale.
        /// </summary>
        internal static string Setting_Raid_W1_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_W1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Spirit Vale on the raid overlay.
        /// </summary>
        internal static string Setting_Raid_W1_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_W1_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W2 / Salvation Pass.
        /// </summary>
        internal static string Setting_Raid_W2_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_W2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Salvation Pass on the raid overlay.
        /// </summary>
        internal static string Setting_Raid_W2_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_W2_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W3 / Stronghold of the Faithful.
        /// </summary>
        internal static string Setting_Raid_W3_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_W3_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Stronghold of the Faithful on the raid overlay.
        /// </summary>
        internal static string Setting_Raid_W3_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_W3_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W4 / Bastion of the Penitent.
        /// </summary>
        internal static string Setting_Raid_W4_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_W4_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Bastion of the Penitent on the raid overlay.
        /// </summary>
        internal static string Setting_Raid_W4_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_W4_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W5 / Hall of Chains.
        /// </summary>
        internal static string Setting_Raid_W5_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_W5_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Hall of Chains on the raid overlay.
        /// </summary>
        internal static string Setting_Raid_W5_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_W5_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W6 / Mythwright Gambit.
        /// </summary>
        internal static string Setting_Raid_W6_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_W6_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Mythwright Gambit on the raid overlay.
        /// </summary>
        internal static string Setting_Raid_W6_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_W6_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W7 / The Key of Ahdashim.
        /// </summary>
        internal static string Setting_Raid_W7_Label {
            get {
                return ResourceManager.GetString("Setting_Raid_W7_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable The Key of Ahdashim on the raid overlay.
        /// </summary>
        internal static string Setting_Raid_W7_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Raid_W7_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable priority stike missions (daily).
        /// </summary>
        internal static string Setting_Stike_Priority {
            get {
                return ResourceManager.GetString("Setting_Stike_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aetherblade Hideout.
        /// </summary>
        internal static string Setting_Strike_AH_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_AH_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align with raids overlay.
        /// </summary>
        internal static string Setting_Strike_AlignWithRaids {
            get {
                return ResourceManager.GetString("Setting_Strike_AlignWithRaids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Strikes to Raid overlay.
        /// </summary>
        internal static string Setting_Strike_AppendToRaid_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_AppendToRaid_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to append the stikes to the end of the raids overlay.
        /// </summary>
        internal static string Setting_Strike_AppendToRaid_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Strike_AppendToRaid_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boneskinner.
        /// </summary>
        internal static string Setting_Strike_BS_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_BS_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_ColBG_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_ColBG_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_ColBG_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Strike_ColBG_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_ColClear_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_ColClear_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_ColClear_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Strike_ColClear_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_ColNotClear_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_ColNotClear_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_ColNotClear_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Strike_ColNotClear_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_ColText_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_ColText_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_ColText_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Strike_ColText_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy layout from raids.
        /// </summary>
        internal static string Setting_Strike_CopyRaids {
            get {
                return ResourceManager.GetString("Setting_Strike_CopyRaids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold War.
        /// </summary>
        internal static string Setting_Strike_CW_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_CW_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_Drag_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_Drag_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_Drag_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Strike_Drag_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable End of Dragons.
        /// </summary>
        internal static string Setting_Strike_Eod {
            get {
                return ResourceManager.GetString("Setting_Strike_Eod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraenir of Jormag.
        /// </summary>
        internal static string Setting_Strike_FoJ_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_FoJ_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_Font_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_Font_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_Font_Tooptip {
            get {
                return ResourceManager.GetString("Setting_Strike_Font_Tooptip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_GridOpacity_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_GridOpacity_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_GridOpactiy_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Strike_GridOpactiy_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harvest Temple.
        /// </summary>
        internal static string Setting_Strike_HT_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_HT_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Icebrood Saga.
        /// </summary>
        internal static string Setting_Strike_IBS {
            get {
                return ResourceManager.GetString("Setting_Strike_IBS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_Icon_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_Icon_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_Icon_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Strike_Icon_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_Keybind_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_Keybind_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_Keybind_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Strike_Keybind_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaineng Overlook.
        /// </summary>
        internal static string Setting_Strike_KO_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_KO_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_LabelDisplay_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_LabelDisplay_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_LabelDisplay_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Strike_LabelDisplay_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_LabelOpacity_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_LabelOpacity_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_LabelOpacity_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Strike_LabelOpacity_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_Layout_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_Layout_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_Layout_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Strike_Layout_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Lion&apos;s Court.
        /// </summary>
        internal static string Setting_Strike_OLC_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_OLC_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_PanelOpacity_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_PanelOpacity_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_PanelOpacity_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Strike_PanelOpacity_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiverpeaks Pass.
        /// </summary>
        internal static string Setting_Strike_SP_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_SP_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_Tooltips_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_Tooltips_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_Tooltips_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Strike_Tooltips_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice and Claw of the Fallen.
        /// </summary>
        internal static string Setting_Strike_VandC_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_VandC_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_Visible_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_Visible_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Setting_Strike_Visible_Tooltip {
            get {
                return ResourceManager.GetString("Setting_Strike_Visible_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whisper of Jormag.
        /// </summary>
        internal static string Setting_Strike_WoJ_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_WoJ_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xunlai Jade Junkyard.
        /// </summary>
        internal static string Setting_Strike_XJJ_Label {
            get {
                return ResourceManager.GetString("Setting_Strike_XJJ_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings window keybind.
        /// </summary>
        internal static string Settings_Keybind_Label {
            get {
                return ResourceManager.GetString("Settings_Keybind_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide this window with a keybind.
        /// </summary>
        internal static string Settings_Keybind_tooltip {
            get {
                return ResourceManager.GetString("Settings_Keybind_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh now.
        /// </summary>
        internal static string Settings_RefreshNow {
            get {
                return ResourceManager.GetString("Settings_RefreshNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable individual End of Dragons strikes.
        /// </summary>
        internal static string Settings_Strike_EOD_Heading {
            get {
                return ResourceManager.GetString("Settings_Strike_EOD_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable individual Icebrood Saga strikes.
        /// </summary>
        internal static string Settings_Strike_IBS_Heading {
            get {
                return ResourceManager.GetString("Settings_Strike_IBS_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options / Keybind.
        /// </summary>
        internal static string SettingsPanel_Dun_Heading_General {
            get {
                return ResourceManager.GetString("SettingsPanel_Dun_Heading_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout / Colors.
        /// </summary>
        internal static string SettingsPanel_Dun_Heading_Layout {
            get {
                return ResourceManager.GetString("SettingsPanel_Dun_Heading_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Selection.
        /// </summary>
        internal static string SettingsPanel_Dun_Heading_PathSelection {
            get {
                return ResourceManager.GetString("SettingsPanel_Dun_Heading_PathSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize the colors by entering a Hex color code..
        /// </summary>
        internal static string SettingsPanel_Raid_Visual_Colors {
            get {
                return ResourceManager.GetString("SettingsPanel_Raid_Visual_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Tip: Google &apos;color picker&apos; for help).
        /// </summary>
        internal static string SettingsPanel_Raid_Visual_ColorsTip {
            get {
                return ResourceManager.GetString("SettingsPanel_Raid_Visual_ColorsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options / Keybind.
        /// </summary>
        internal static string SettingsPanel_Raids_Heading_General {
            get {
                return ResourceManager.GetString("SettingsPanel_Raids_Heading_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout / Colors.
        /// </summary>
        internal static string SettingsPanel_Raids_Heading_Layout {
            get {
                return ResourceManager.GetString("SettingsPanel_Raids_Heading_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wing Selection.
        /// </summary>
        internal static string SettingsPanel_Raids_Heading_WingSelection {
            get {
                return ResourceManager.GetString("SettingsPanel_Raids_Heading_WingSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikes Selection.
        /// </summary>
        internal static string SettingsPanel_Strikes_Heading_Selection {
            get {
                return ResourceManager.GetString("SettingsPanel_Strikes_Heading_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customization options.
        /// </summary>
        internal static string SettingsPanel_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPanel_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeons.
        /// </summary>
        internal static string SettingsPanel_Tab_Dunegons {
            get {
                return ResourceManager.GetString("SettingsPanel_Tab_Dunegons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsPanel_Tab_General {
            get {
                return ResourceManager.GetString("SettingsPanel_Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raids.
        /// </summary>
        internal static string SettingsPanel_Tab_Raids {
            get {
                return ResourceManager.GetString("SettingsPanel_Tab_Raids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikes.
        /// </summary>
        internal static string SettingsPanel_Tab_Strikes {
            get {
                return ResourceManager.GetString("SettingsPanel_Tab_Strikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlays can use the same keybind.
        /// </summary>
        internal static string SharedKeybind {
            get {
                return ResourceManager.GetString("SharedKeybind", resourceCulture);
            }
        }
    }
}
