//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaidClears.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RaidClears.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raid Clears.
        /// </summary>
        internal static string Module_Title {
            get {
                return ResourceManager.GetString("Module_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        internal static string ModuleSettings_OpenSettings {
            get {
                return ResourceManager.GetString("ModuleSettings_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable raid overlay.
        /// </summary>
        internal static string Raid_OverlayEnable {
            get {
                return ResourceManager.GetString("Raid_OverlayEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options / Keybind.
        /// </summary>
        internal static string SettingsPanel_Raids_Heading_General {
            get {
                return ResourceManager.GetString("SettingsPanel_Raids_Heading_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout / Colors.
        /// </summary>
        internal static string SettingsPanel_Raids_Heading_Layout {
            get {
                return ResourceManager.GetString("SettingsPanel_Raids_Heading_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wing Selection.
        /// </summary>
        internal static string SettingsPanel_Raids_Heading_WingSelection {
            get {
                return ResourceManager.GetString("SettingsPanel_Raids_Heading_WingSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customization options.
        /// </summary>
        internal static string SettingsPanel_Subtitle {
            get {
                return ResourceManager.GetString("SettingsPanel_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dungeons.
        /// </summary>
        internal static string SettingsPanel_Tab_Dunegons {
            get {
                return ResourceManager.GetString("SettingsPanel_Tab_Dunegons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsPanel_Tab_General {
            get {
                return ResourceManager.GetString("SettingsPanel_Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raids.
        /// </summary>
        internal static string SettingsPanel_Tab_Raids {
            get {
                return ResourceManager.GetString("SettingsPanel_Tab_Raids", resourceCulture);
            }
        }
    }
}
